services:
  app:
    container_name: movieclub_dev_app
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: movieclub_dev_db
    image: postgres:17-alpine
    restart: on-failure:3
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test:
    container_name: movieclub_test_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: test
      PORT: ${TEST_PORT}
      POSTGRES_DB: movieclub_test_db
    depends_on:
      - db
    command: ["pnpm", "test"] # Runs your test suite