services:
  app:
    container_name: movieclub_dev_app
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    container_name: movieclub_dev_db
    image: postgres:17-alpine
    restart: on-failure:3
    ports:
      - "5433:5432"
    env_file:
      - .env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: movieclub_dev_redis
    image: redis:latest
    restart: on-failure:3
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis_pw_123"]
    environment:
      - REDIS_PASSWORD=redis_pw_123

volumes:
  postgres_data_dev:
