services:
  app:
    container_name: movieclub_prod_app
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: movieclub_prod_db
    image: postgres:17-alpine
    restart: on-failure:3
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
